---
- hosts: all
  become: yes
  tasks:
    - name: Install the package openjdk-8 on Ubuntu server
      apt:
        name: openjdk-8-jre
        state: present
    
    - name: i want to install open jdk-8 on redhat server
      yum:
        name: java-1.8.0-openjdk
        state: present