---
- hosts: javaserver
  become: yes
  tasks:
    - name: Run linux command to get fully qualified hostname
      command: hostname -f
      register: myresult

    - name: Display the output of the linux command
      debug:
        msg: "{{ myresult }}"
    - name: Install git
      apt:
        name: gitt
        state: present
      when: myresult.stderr == ""

    - name: Install tree
      apt:
        name: tree  # Corrected to install tree
        state: present
      when: myresult.stderr != ""