---
- hosts: all
  become: yes
  tasks:
    - name: Install tree package
      apt:
        name: tree
        state: present
    - name: Install apache2 package
      apt:
        name: apache2
        state: absent
    - name: Start apache2 service
      service:
        name: apache2
        state: started
